# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20)),
                ('hotel_id', models.IntegerField()),
                ('hotel_url', models.URLField()),
                ('hotel_front_img_url', models.URLField()),
                ('hotel_front_img_path', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '酒店首页信息',
                'verbose_name': '酒店首页信息',
            },
        ),
    ]
