# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentspider', '0002_hoteldetail_reply_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetail',
            name='commentExt_checkInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='commentExt_roomNum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='commentExt_roomTypeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='commentExt_roomTypeName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='guest_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='guest_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentspider.HotelIndex'),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='replys_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='replys_createTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='replys_replyId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply_image',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentspider.HotelDetail'),
        ),
        migrations.AlterField(
            model_name='reply_image',
            name='guset_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
