# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentspider', '0003_auto_20170728_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='评论网站')),
            ],
            options={
                'verbose_name_plural': '评论网站',
                'verbose_name': '评论网站',
            },
        ),
        migrations.AddField(
            model_name='hotelindex',
            name='wherefrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentspider.WhereFrom'),
        ),
    ]
