# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentspider', '0004_auto_20170805_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetail',
            name='wherefrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentspider.WhereFrom'),
        ),
    ]
